theme: minima
title: This is Aaron Tsui
author: Aaron Tsui
email: atsui@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page! This is about Aaron Tsui.

# social links
instagram_username: aaron.tsui_

show_excerpts: true # set to false to remove excerpts on the homepage
